/** Rótulos dos "sistemas" (seções) — fonte única para MetaAdmin, MetaNutri e `buildPatientLabSectionsFromOrder` (/meta, metapersonal). */
export const LAB_SECTION_LABELS_PT: Record<string, string> = {
  metabolismoBasico: 'Metabolismo Glicídico Básico',
  metabolismoAvancado: 'Metabolismo Avançado / Resistência Insulínica',
  renalMetabolico: 'Função Renal e Metabólica',
  inflamacaoRiscoCardio: 'Inflamação / Risco Cardiovascular',
  lipideos: 'Perfil Lipídico',
  hepatobiliar: 'Função Hepática e Biliar',
  gastroPancreatico: 'Gastrointestinal / Pancreático',
  tireoide: 'Tireoide',
  hormoniosSexuais: 'Hormônios Sexuais',
  eixoAdrenalEstresse: 'Eixo Adrenal / Estresse',
  performanceRecuperacao: 'Performance / Recuperação',
  estadoNutricionalInflamatorio: 'Estado Nutricional / Inflamatório',
  hemograma: 'Hemograma',
  infeccoesTriagem: 'Infecções / Triagem',
  metaisToxicos: 'Metais Tóxicos',
  parasitologia: 'Parasitologia',
  marcadoresTumorais: 'Marcadores Tumorais Complementares',
  estresseOxidativo: 'Estresse Oxidativo / Defesa Antioxidante',
};
