import {
  STEP_PERFIL_METABOLICO_ALIMENTACAO,
  STEP_PERFIL_METABOLICO_ATIVIDADE,
  STEP_PERFIL_METABOLICO_BARREIRAS,
  STEP_PERFIL_METABOLICO_ENERGIA,
  STEP_PERFIL_METABOLICO_EXPECTATIVA,
  STEP_PERFIL_METABOLICO_HISTORICO,
  STEP_PERFIL_METABOLICO_MEDICAMENTOS,
  STEP_PERFIL_METABOLICO_SONO,
} from '@/lib/meta/perfilMetabolicoV3Chat';

export const PERFIL_METABOLICO_CARD_ID_TO_STEP: Record<string, number> = {
  sono: STEP_PERFIL_METABOLICO_SONO,
  atividade: STEP_PERFIL_METABOLICO_ATIVIDADE,
  alimentacao: STEP_PERFIL_METABOLICO_ALIMENTACAO,
  energia: STEP_PERFIL_METABOLICO_ENERGIA,
  historico: STEP_PERFIL_METABOLICO_HISTORICO,
  medicamentos: STEP_PERFIL_METABOLICO_MEDICAMENTOS,
  barreiras: STEP_PERFIL_METABOLICO_BARREIRAS,
  expectativa: STEP_PERFIL_METABOLICO_EXPECTATIVA,
};

export function getPerfilMetabolicoStepForCard(cardId: string): number | null {
  return PERFIL_METABOLICO_CARD_ID_TO_STEP[cardId] ?? null;
}
