export const SYMPTOM_OPTIONS = [
  // Sintomas básicos
  'Visão borrada',
  'Cefaleia',
  'Dificuldade para leitura',
  'Dor nos olhos',
  'Fotofobia',
  'Visão dupla',
  'Olhos secos',
  'Coceira nos olhos',
  'Vermelhidão',
  'Lacrimejamento',
  'Sensação de corpo estranho',
  'Fadiga visual',
  'Dificuldade para enxergar de longe',
  'Dificuldade para enxergar de perto',
  'Sensibilidade à luz',
  'Dor de cabeça',
  'Náusea',
  'Tontura',
  'Perda de visão periférica',
  'Manchas na visão',
  'Flutuações na visão',
  'Dificuldade para dirigir à noite',
  'Dificuldade para ver cores',
  'Visão embaçada ao acordar',
  'Ardor nos olhos',
  
  // Sintomas visuais expandidos
  'Manchas móveis (moscas volantes)',
  'Flashes de luz',
  'Sensação de olho seco',
  'Lacrimejamento excessivo',
  'Ardência ocular',
  'Vermelhidão nos olhos',
  'Secreção ocular',
  'Pálpebras pesadas',
  'Sensibilidade à luz artificial',
  'Visão tremida ou com "ondas"',
  'Visão distorcida (metamorfopsia)',
  'Dificuldade para reconhecer rostos',
  'Campo de visão restrito',
  'Dores orbitárias',
  'Sensação de pressão ocular',
  'Visão com cores desbotadas',
  'Dificuldade para acompanhar linhas de texto',
  'Piora da visão após esforço visual',
  'Desconforto ao usar computador/celular',
  'Necessidade de aproximar objetos para ler',
  'Necessidade de afastar objetos para ler'
];

export const DIAGNOSIS_OPTIONS = [
  // Diagnósticos básicos
  'Catarata',
  'Ceratocone',
  'Cirurgia refrativa',
  'Glaucoma',
  'Retinopatia diabética',
  'Degeneração macular',
  'Astigmatismo',
  'Miopia',
  'Hipermetropia',
  'Presbiopia',
  'Estrabismo',
  'Ambliopia',
  'Uveíte',
  'Conjuntivite',
  'Blefarite',
  'Pterígio',
  'Pinguecula',
  'Descolamento de retina',
  'Oclusão de veia retiniana',
  'Oclusão de artéria retiniana',
  'Nevos coroidais',
  'Tumores oculares',
  'Trauma ocular',
  
  // Diagnósticos expandidos
  'Retinopatia serosa central (CSC)',
  'Oclusão de veia central ou ramo',
  'Edema macular diabético',
  'Edema macular cistóide',
  'Buraco de mácula',
  'Membrana epirretiniana',
  'Hemorragia vítrea',
  'Glaucoma de ângulo aberto',
  'Glaucoma de ângulo fechado',
  'Suspeita de glaucoma',
  'Hifema (sangue na câmara anterior)',
  'Hemorragia subconjuntival recorrente',
  'Neurite óptica',
  'Atrofia óptica',
  'Doença autoimune ocular (ex: Sjögren)',
  'Toxoplasmose ocular',
  'Coloboma',
  'Nistagmo',
  'Pseudofacia (lente intraocular)',
  'Ametropia elevada',
  'Distrofias retinianas hereditárias',
  'Nenhum'
]; 